"""
Time-Dependent Electromagnetic Field Simulation for Relativistic Charged Particles

This module computes and visualizes the EM fields (E and B) generated by a moving
relativistic charged particle using analytic Liénard-Wiechert expressions.

Physics Model:
    E_x = -e/(4πε₀) * (1-β²) / (1-β²sin²θ)^(3/2) * d / R²
    E_y = 0
    E_z = -e/(4πε₀) * (1-β²) / (1-β²sin²θ)^(3/2) * (v(t-t₀)-z₀) / R²
    
    B_x = 0
    B_y = (v/c²) * E_x
    B_z = 0

Where:
    β = sqrt(1 - 1/γ²)
    γ = Ek/0.511 + 1
    v = β * c
    R = sqrt(d² + (v(t-t₀)-z₀)²)
    sin(θ) = d / R
"""

import numpy as np

# =============================================================================
# CONSTANTS
# =============================================================================
Q_E = 1.6e-19           # Elementary charge (Coulombs)
EPSILON_0 = 8.854e-12   # Permittivity of free space (F/m)
PI = 3.141592653589793  # Pi
M_E = 9.109e-31         # Electron mass (kg)
C = 3e8                 # Speed of light (m/s)

# =============================================================================
# SIMULATION PARAMETERS
# =============================================================================


# =============================================================================
# PHYSICS CALCULATIONS
# =============================================================================

def calculate_relativistic_parameters(Ek_MeV):
    """
    Calculate relativistic parameters from kinetic energy.
    
    Args:
        Ek_MeV: Kinetic energy in MeV
        
    Returns:
        gamma: Lorentz factor
        beta: Dimensionless velocity (v/c)
        v: Velocity in m/s
    """
    gamma = Ek_MeV / 0.511 + 1  # Convert MeV to γ
    beta = np.sqrt(1 - 1 / (gamma**2))
    v = beta * C
    return gamma, beta, v


def calculate_EM_fields(t, gamma, beta, v, d, t_0, z_0):
    """
    Calculate electromagnetic field components at time t.
    
    Args:
        t: Time array (seconds)
        gamma: Lorentz factor
        beta: Dimensionless velocity
        v: Velocity (m/s)
        d: Perpendicular distance (m)
        t_0: Reference time (s)
        z_0: Reference position (m)
        
    Returns:
        E_x, E_y, E_z: Electric field components
        B_x, B_y, B_z: Magnetic field components
        E_magnitude: |E| field strength
    """
    # Calculate R: distance from observation point to particle
    R = np.sqrt(d**2 + (v * (t - t_0) - z_0)**2)
    
    # sin(θ) and sin²(θ)
    sin_theta = d / R
    sin2_theta = sin_theta**2
    
    # Denominator factor: (1 - β²sin²θ)^(3/2)
    denominator_factor = (1 - beta**2 * sin2_theta)**(3/2)
    
    # Common factor for E field
    const_factor = -Q_E / (4 * PI * EPSILON_0) * (1 - beta**2) / denominator_factor
    
    # Electric field components
    E_x = const_factor * d / (R**2)
    E_y = np.zeros_like(t)  # Always zero
    E_z = const_factor * (v * (t - t_0) - z_0) / (R**2)
    
    # Magnetic field components
    B_x = np.zeros_like(t)  # Always zero
    B_y = (v / (C**2)) * E_x
    B_z = np.zeros_like(t)  # Always zero
    
    # Field magnitudes
    E_magnitude = np.sqrt(E_x**2 + E_y**2 + E_z**2)
    B_magnitude = np.sqrt(B_x**2 + B_y**2 + B_z**2)
    
    return E_x, E_y, E_z, B_x, B_y, B_z, E_magnitude, B_magnitude



# =====================
# Module API function
# =====================
def compute_em_fields(
    t_start: float,
    t_end: float,
    num_points: int,
    Ek: float = 10.0,
    d: float = 1.0,
    t_0: float = 0.0,
    z_0: float = None
) -> tuple:
    """
    Compute the time-dependent EM fields for a single relativistic electron.
    Args:
        t_start: Start time (s)
        t_end: End time (s)
        num_points: Number of time points
        Ek: Kinetic energy (MeV)
        d: Perpendicular distance from trajectory (m)
        t_0: Reference time (s)
        z_0: Reference position (m). If None, uses t_0 / C.
    Returns:
        t: time array
        E_x, E_y, E_z: electric field components
        B_x, B_y, B_z: magnetic field components
        E_mag: |E| field magnitude
        B_mag: |B| field magnitude
    """
    if z_0 is None:
        z_0 = t_0 / C
    gamma, beta, v = calculate_relativistic_parameters(Ek)
    t = np.linspace(t_start, t_end, num_points)
    E_x, E_y, E_z, B_x, B_y, B_z, E_mag, B_mag = calculate_EM_fields(
        t, gamma, beta, v, d, t_0, z_0
    )
    return t, E_x, E_y, E_z, B_x, B_y, B_z, E_mag, B_mag
