"""
Time-Dependent Electromagnetic Field Simulation for Relativistic Charged Particles

This module computes and visualizes the EM fields (E and B) generated by a moving
relativistic charged particle using analytic Liénard-Wiechert expressions.

Physics Model:
    E_x = -e/(4πε₀) * (1-β²) / (1-β²sin²θ)^(3/2) * d / R²
    E_y = 0
    E_z = -e/(4πε₀) * (1-β²) / (1-β²sin²θ)^(3/2) * (v(t-t₀)-z₀) / R²
    
    B_x = 0
    B_y = (v/c²) * E_x
    B_z = 0

Where:
    β = sqrt(1 - 1/γ²)
    γ = Ek/0.511 + 1
    v = β * c
    R = sqrt(d² + (v(t-t₀)-z₀)²)
    sin(θ) = d / R
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib

# 设置中文字体和负号显示（如有需要）
matplotlib.rcParams['font.sans-serif'] = ['Heiti TC', 'STHeiti', 'SimHei', 'Arial Unicode MS']
matplotlib.rcParams['axes.unicode_minus'] = False  # Use ASCII minus

# =============================================================================
# CONSTANTS
# =============================================================================
# Q_E = 1.6e-19           # Elementary charge (Coulombs)
Q_E = 1.6e-9
EPSILON_0 = 8.854e-12   # Permittivity of free space (F/m)
PI = 3.141592653589793  # Pi
M_E = 9.109e-31         # Electron mass (kg)
C = 3e8                 # Speed of light (m/s)

# =============================================================================
# SIMULATION PARAMETERS
# =============================================================================
Ek = 10.0               # Kinetic energy (MeV)
d = 1.0                 # Perpendicular distance from trajectory (m)
t_0 = 0              # Initial time reference
z_0 = abs(t_0) / C           # Initial position reference

# Time window for simulation
t_start = -1e-8        # seconds
t_end   =  1e-8        # seconds
num_points = 1000      # Number of time points

# =============================================================================
# PHYSICS CALCULATIONS
# =============================================================================

def calculate_relativistic_parameters(Ek_MeV):
    """
    Calculate relativistic parameters from kinetic energy.
    
    Args:
        Ek_MeV: Kinetic energy in MeV
        
    Returns:
        gamma: Lorentz factor
        beta: Dimensionless velocity (v/c)
        v: Velocity in m/s
    """
    gamma = Ek_MeV / 0.511 + 1  # Convert MeV to γ
    beta = np.sqrt(1 - 1 / (gamma**2))
    v = beta * C
    return gamma, beta, v


def calculate_EM_fields(t, gamma, beta, v, d, t_0, z_0):
    """
    Calculate electromagnetic field components at time t.
    
    Args:
        t: Time array (seconds)
        gamma: Lorentz factor
        beta: Dimensionless velocity
        v: Velocity (m/s)
        d: Perpendicular distance (m)
        t_0: Reference time (s)
        z_0: Reference position (m)
        
    Returns:
        E_x, E_y, E_z: Electric field components
        B_x, B_y, B_z: Magnetic field components
        E_magnitude: |E| field strength
    """
    # Calculate R: distance from observation point to particle
    R = np.sqrt(d**2 + (v * (t - t_0) - z_0)**2)
    
    # sin(θ) and sin²(θ)
    sin_theta = d / R
    sin2_theta = sin_theta**2
    
    # Denominator factor: (1 - β²sin²θ)^(3/2)
    denominator_factor = (1 - beta**2 * sin2_theta)**(3/2)
    
    # Common factor for E field
    const_factor = -Q_E / (4 * PI * EPSILON_0) * (1 - beta**2) / denominator_factor
    
    # Electric field components
    E_x = const_factor * d / (R**2)
    E_y = np.zeros_like(t)  # Always zero
    E_z = const_factor * (v * (t - t_0) - z_0) / (R**2)
    
    # Magnetic field components
    B_x = np.zeros_like(t)  # Always zero
    B_y = (v / (C**2)) * E_x
    B_z = np.zeros_like(t)  # Always zero
    
    # Field magnitudes
    E_magnitude = np.sqrt(E_x**2 + E_y**2 + E_z**2)
    B_magnitude = np.sqrt(B_x**2 + B_y**2 + B_z**2)
    
    return E_x, E_y, E_z, B_x, B_y, B_z, E_magnitude, B_magnitude


# =============================================================================
# MAIN SIMULATION
# =============================================================================

def main():
    """Main simulation and plotting routine."""
    
    print("=" * 70)
    print("EM Field Simulation for Relativistic Charged Particle")
    print("=" * 70)
    print(f"\nParameters:")
    print(f"  Kinetic Energy: {Ek} MeV")
    print(f"  Perpendicular Distance (d): {d} m")
    print(f"  Time Window: [{t_start:.2e}, {t_end:.2e}] s")
    print(f"  Number of Points: {num_points}")
    
    # Calculate relativistic parameters
    gamma, beta, v = calculate_relativistic_parameters(Ek)
    print(f"\nRelativistic Parameters:")
    print(f"  γ (Lorentz factor): {gamma:.4f}")
    print(f"  β (v/c): {beta:.6f}")
    print(f"  v (velocity): {v:.4e} m/s")
    
    # Create time array
    time = np.linspace(t_start, t_end, num_points)
    
    # Calculate fields
    E_x, E_y, E_z, B_x, B_y, B_z, E_mag, B_mag = calculate_EM_fields(
        time, gamma, beta, v, d, t_0, z_0
    )
    
    # Convert time to nanoseconds for better readability
    time_ns = time * 1e9
    
    print(f"\nField Calculations Complete")
    print(f"  Max |E|: {np.max(E_mag):.4e} V/m")
    print(f"  Max |B|: {np.max(B_mag):.4e} T")
    
    # =============================================================================
    # PLOTTING
    # =============================================================================
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    fig.suptitle('忽略空间分布的电子束团产生的电磁场脉冲', fontsize=16, fontweight='bold')
    
    # Plot 1: Electric field magnitude vs time
    axes[0, 0].plot(time_ns, E_mag, 'b-', linewidth=2, label='|E|')
    axes[0, 0].set_xlabel('时间 (ns)', fontsize=11)
    axes[0, 0].set_ylabel('电场幅值 (V/m)', fontsize=11)
    axes[0, 0].set_title('电场脉冲', fontsize=12, fontweight='bold')
    axes[0, 0].grid(True, alpha=0.3)
    axes[0, 0].legend(fontsize=10)
    
    # Plot 2: Electric field components
    axes[0, 1].plot(time_ns, E_x, 'r-', linewidth=1.5, label='E_x', alpha=0.8)
    axes[0, 1].plot(time_ns, E_z, 'g-', linewidth=1.5, label='E_z', alpha=0.8)
    axes[0, 1].set_xlabel('时间 (ns)', fontsize=11)
    axes[0, 1].set_ylabel('电场分量 (V/m)', fontsize=11)
    axes[0, 1].set_title('电场分量', fontsize=12, fontweight='bold')
    axes[0, 1].grid(True, alpha=0.3)
    axes[0, 1].legend(fontsize=10)
    
    # Plot 3: Magnetic field magnitude vs time
    axes[1, 0].plot(time_ns, B_mag, 'purple', linewidth=2, label='|B|')
    axes[1, 0].set_xlabel('时间 (ns)', fontsize=11)
    axes[1, 0].set_ylabel('磁场幅值e (T)', fontsize=11)
    axes[1, 0].set_title('磁场脉冲', fontsize=12, fontweight='bold')
    axes[1, 0].grid(True, alpha=0.3)
    axes[1, 0].legend(fontsize=10)
    
    # Plot 4: Magnetic field component (B_y)
    axes[1, 1].plot(time_ns, B_y, 'orange', linewidth=2, label='B_y')
    axes[1, 1].set_xlabel('时间 (ns)', fontsize=11)
    axes[1, 1].set_ylabel('磁场分量 (T)', fontsize=11)
    axes[1, 1].set_title('磁场分量 (B_y)', fontsize=12, fontweight='bold')
    axes[1, 1].grid(True, alpha=0.3)
    axes[1, 1].legend(fontsize=10)
    
    plt.tight_layout()
    # plt.show()
    plt.savefig('EM_field_pulses_single_electron.png', dpi=600)
    
    print("\n" + "=" * 70)
    print("Plot generated successfully!")
    print("=" * 70)


# =============================================================================
# TROUBLESHOOTING NOTES
# =============================================================================
"""
If the plot window does not appear, confirm that:
    1. Matplotlib backend is working: try `pip install matplotlib`
    2. NumPy is installed: `pip install numpy`
    3. You're running the script directly (not in REPL)
    4. If using VS Code, ensure Python extension is installed

To run this script:
    python EM_field.py
"""

if __name__ == '__main__':
    main()
